[package]
name = "gpui-app"
version = "0.1.0"
edition = "2024"
rust-version = "1.99.0"

[dependencies]
dirs = "7.0.0"
futures-lite = "2.6.1"
gpui-kit = "0.7.0"
mundy = { version = "0.2.3", default-features = false, features = ["async-io", "accent-color"] }
serde = { version = "1.0.229", features = ["derive"] }
yaml_serde = "0.10.7"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true
